version: "3"

services:
  app:
    image: muchikon/networking
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    depends_on:
      - db
    ports:
      - "4000:3000"
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.labels.ambiente == desa]

  db:
    image: mongo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    
